# Generated by Django 2.2.5 on 2019-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191002_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='fillStyle',
            field=models.CharField(help_text='background color for prize on wheel', max_length=7, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(default='prize', max_length=200, verbose_name='prize name'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='textFillStyle',
            field=models.CharField(max_length=7, verbose_name='text color'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='textFontSize',
            field=models.IntegerField(default=12, help_text='prize text size on wheel', verbose_name='font size'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='fillStyle',
            field=models.CharField(default='text', help_text='image or text', max_length=200),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='innerRadius',
            field=models.IntegerField(default=0, help_text='inside radius for donut wheel', verbose_name='inside radius'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='numSegments',
            field=models.IntegerField(default=6, help_text='number of prizes on game wheel', verbose_name='number of prizes'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='outerRadius',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='textFontFamily',
            field=models.CharField(default='Verdana', max_length=200, verbose_name='font family'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='textFontSize',
            field=models.IntegerField(default=24, verbose_name='font size'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='textOrientation',
            field=models.CharField(default='vertical', help_text='vertical or horizontal', max_length=10),
        ),
    ]
