# Generated by Django 2.2.5 on 2019-10-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wheel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='user',
            new_name='created_by',
        ),
    ]
