# Generated by Django 2.2.5 on 2019-09-24 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='spinToStop', max_length=200)),
                ('duration', models.IntegerField(default=10)),
                ('spins', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wheel of Fun', max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('showDescription', models.BooleanField(default=False)),
                ('numSegments', models.IntegerField(default=6)),
                ('innerRadius', models.IntegerField(default=25)),
                ('outerRadius', models.IntegerField(default=125)),
                ('fillStyle', models.CharField(default='text', max_length=200)),
                ('textFontFamily', models.CharField(default='Verdana', max_length=200)),
                ('textFontSize', models.IntegerField(default=24)),
                ('textOrientation', models.CharField(default='vertical', max_length=10)),
                ('textAlignment', models.CharField(default='outer', max_length=50)),
                ('animation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Animation')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fillStyle', models.CharField(max_length=7)),
                ('textFillStyle', models.CharField(max_length=7)),
                ('textFontSize', models.IntegerField(default=12)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Wheel')),
            ],
        ),
    ]
