# Generated by Django 2.2.5 on 2019-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_segment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='description',
            field=models.CharField(default='You have won', max_length=400),
        ),
    ]
